name: ETF Analysis

on:
  schedule:
    # 每天台灣時間 09:30 運行 (UTC+8)
    # 注意: GitHub Actions 使用 UTC 時間,所以需要調整
    - cron: "0 1 * * 1-5" # UTC 01:00 (台灣時間 9:00), 週一到週五
  workflow_dispatch: # 保留手動觸發選項

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python dependencies
        uses: ./.github/actions/install_python_dependencies

      - name: Run analysis
        env:
          LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}
        run: python etf_analysis.py
